### ISSUE TITLE
Not a CR2W file error

### ISSUE THREAD

**Issue by redtankbai** [dingdio/witcher3-maya-animation#6]
hi dingdio,

i got some problem when open w3 files with your customized WolvenKit tool

when i mark a w2anims file and add to Mod with button, i only got a 0KB file, no data been dumped

any idea?

**Comment by redtankbai** [comment]
to make it clear, i can open and browser all game file bundle with no problem, the only issue is when try export or double click marked files, CR2W error happens

**Comment by redtankbai** [comment]
[2021/8/27 21:16:10]: Ionic.Zlib.ZlibException: Bad state (incorrect header check)
   at Ionic.Zlib.InflateManager.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at WolvenKit.Bundles.BundleItem.Extract(Stream output) location F:\sourcetree\Wolven-kit\WolvenKit.Bundles\BundleItem.cs:line 101
   at WolvenKit.Bundles.BundleItem.Extract(BundleFileExtractArgs e) location F:\sourcetree\Wolven-kit\WolvenKit.Bundles\BundleItem.cs:line 110
   at WolvenKit.frmMain.AddToMod(WitcherListViewItem item, Boolean skipping, List`1 managers, Boolean AddAsDLC) location F:\sourcetree\Wolven-kit\WolvenKit\Forms\frmMain.cs:line 1235

**Comment by redtankbai** [comment]
so is that your tool only work with special version of w3? could you provide withers3.exe version number? thx

**Comment by redtankbai** [comment]
done, thx
